components:
  schemas:
    Crop:
      properties:
        id:
          type: string
          example: 1DiqY12zl
          readOnly: true
        origin:
          $ref: '#/components/schemas/Origin'
        year:
          type: integer
      required:
        - origin
        - year
