components:
  schemas:
    Roast:
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        region:
          $ref: '#/components/schemas/Origin'
